# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['generate_sequence']

# Cell
import random

def generate_sequence(length, alphabet):
	"Generates a sequence of a given length using a given alphabet."
	return [random.choice(alphabet) for x in range(length)]